### ISSUE TITLE
Infografía Realidad Aumentada

### ISSUE THREAD

**Issue by Brendalp** [SistemasTecTlaxiaco/infografia-Brendalp#1]
[Infografia Realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Brendalp/files/8054938/Infografia.Realidad.aumentada.pdf)

**Comment by MarcosJonathan17** [comment]
muy bien, exelente trabajo, buen diseño he informacion detallada: califiacion 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
