### ISSUE TITLE
Infografía Ingeniería de software-BrendaLópezPérez

### ISSUE THREAD

**Issue by Brendalp** [SistemasTecTlaxiaco/infografia-Brendalp#2]
[Infografia_BrendaLópezPérez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Brendalp/files/6178719/Infografia_BrendaLopezPerez.pdf)

**Comment by garaudy12** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
